This directory contains the R code used to generate the simulation results
presented in the article: "Design and analysis of group sequential trials for
repeated measurements when pipeline data
occurs: a tutorial". It is organized as follows:
- *the BATCH files* define the simulation studies for a single interim
  and two interim. Each file was excecuted using 18 different
  parameters (missing, binding, constraint on ck, accrual rate, effect
  size) 100 times. Each time corresponds to a different id (obtain
  using =Sys.getenv("SGE_TASK_ID")= in R) and therefore a different
  seed when randomly generating the data. The output of the
  simulations were saved in a =Results= directory, not uploaded on
  Github to save space but available upon request.
- *the FCT file* called by the BATCH file.
- *the FIGURE files* generate figures for the article.
- *the SLURM files* run the BATCH files on a computer cluster in parallel.
- *the BUILD file* gather the results of the various simulations by
  reading the data in the =Results= directory. It converts them into a
  a single table (=data.table= format) and exported in the
  =Results-built= directory, not uploaded on Github to save space but
  available upon request.
- *the FIGURE directory* R code for figure 6 in the article
- *the FIGURE directory* R code  for generating table 1 and supplementary tables B, C, D in the article


#+BEGIN_SRC R :exports both :results output :session *R* :cache no
library(DelayedGSD)
library(data.table)
library(ggplot2)
library(xtable)
sessionInfo()
#+END_SRC

#+RESULTS:
#+begin_example
data.table 1.14.2 using 4 threads (see ?getDTthreads).  Latest news: r-datatable.com
Advarselsbesked:
pakke 'ggplot2' blev bygget under R version 4.2.3
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=Danish_Denmark.utf8  LC_CTYPE=Danish_Denmark.utf8   
[3] LC_MONETARY=Danish_Denmark.utf8 LC_NUMERIC=C                   
[5] LC_TIME=Danish_Denmark.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xtable_1.8-4      ggplot2_3.4.3     data.table_1.14.2 DelayedGSD_0.0.5 

loaded via a namespace (and not attached):
 [1] fansi_1.0.4      withr_2.5.1      dplyr_1.1.3      utf8_1.2.3      
 [5] grid_4.2.0       R6_2.5.1         lifecycle_1.0.3  gtable_0.3.4    
 [9] magrittr_2.0.3   scales_1.2.1     pillar_1.9.0     rlang_1.1.1     
[13] cli_3.6.1        generics_0.1.3   vctrs_0.6.3      glue_1.6.2      
[17] munsell_0.5.0    compiler_4.2.0   pkgconfig_2.0.3  colorspace_2.1-0
[21] tidyselect_1.2.0 tibble_3.2.1
#+end_example
