This directory contains the R code used to generate the simulation results
presented in the article: "Design and analysis of group sequential trials for
repeated measurements when pipeline data
occurs: a tutorial". It is organized as follows:
- *the BATCH files* define the simulation studies for a single interim
  and two interim. Each file was excecuted using 18 different
  parameters (missing, binding, constraint on ck, accrual rate, effect
  size) 100 times. Each time corresponds to a different id (obtain
  using =Sys.getenv("SGE_TASK_ID")= in R) and therefore a different
  seed when randomly generating the data. The output of the
  simulations were saved in a =Results= directory, not uploaded on
  Github to save space but available upon request.
- *the FCT file* called by the BATCH file.
- *the FIGURE files* generate figures for the article.
- *the SLURM files* run the BATCH files on a computer cluster in parallel.
- *the BUILD file* gather the results of the various simulations by
  reading the data in the =Results= directory. It converts them into a
  a single table (=data.table= format) and exported in the
  =Results-built= directory, not uploaded on Github to save space but
  available upon request.
- *the FIGURE directory* R code for figure 6 in the article
- *the FIGURE directory* R code  for generating table 1 and supplementary tables B, C, D in the article


#+BEGIN_SRC R :exports both :results output :session *R* :cache no
library(DelayedGSD)
sessionInfo()
#+END_SRC

#+RESULTS:
#+begin_example
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux 8.9 (Ootpa)

Matrix products: default
BLAS:   /maps/direct/software/R/4.1.2/lib64/R/lib/libRblas.so
LAPACK: /maps/direct/software/R/4.1.2/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] DelayedGSD_0.0.7

loaded via a namespace (and not attached):
[1] compiler_4.1.2
#+end_example
